# -*- coding: utf-8 -*-
"""finalKeywordExtractionandTagging.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JW_u1yidoxgfR38wk0jxKkvxs4V0EjBM
"""
import wordcloud

import nltk
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('averaged_perceptron_tagger', quiet=True)

import numpy as np # linear algebra
import pandas as pd 
import re
import csv
import string

import spacy
from tqdm import tqdm
import time
import pickle
import tensorflow as tf
import tensorflow_hub as hub

import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize

from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.linear_model import LogisticRegression

# Binary Relevance
from sklearn.multiclass import OneVsRestClassifier

# Performance metric
from sklearn.metrics import f1_score

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

from sklearn.svm import SVC

from skmultilearn.problem_transform import BinaryRelevance
from sklearn.naive_bayes import GaussianNB

from autocorrect import Speller
from rake_nltk import Rake
from sklearn import metrics

#from sklearn.externals import joblib

import yake             
#Cleanse data for better analysis
stopwords = set(stopwords.words("english"))
spell = Speller(lang='en')

selected_list = ['useful course', 'useful investment', 'practical course', 'modern course', 'innovative course','great course', 'great learn', 'basic course', 'basic learn', 'basic learning', 'helpful course', 
                 'deep course', 'helpful insight', 'deep insight', 'respected','lots of homework','participation matters', 'inspirational course', 'test heavy', 'group projects', 'clear grading', 'amazing lectures', 
                 'lecture heavy', 'extra credit', 'tough grader', 'theory intensive', 'practical knowledge','helpful knowledge', 'deep knowledge','intelligent professor','intelligent explanation', 'practical teach',
                 'nice course', 'nice professor', 'good course', 'good professor', 'basic course', 'basic professor', 'nice topic', 'interesting topic', 'enthusiastic experience', 'enthusiastic course', 'good engaging', 
                 'good experience', 'informative course', 'informative learn','overall good','good instructor','exhaustive course', 'great coverage', 'exhaustive coverage','strongly recommend', 'money worth', 'good overview',
                 'interested topic', 'general course','general level','clear concept','clear approach', 'practical approach','best gain','great understanding', 'deep understanding','perfect content', 'learnt lot', 'useful skill',
                 'excellent course', 'broad course','strong elaboration','basic tool','available purpose','basic application', 'available application', 'interested knowledge','great experience', 'practical experience',
                 'general concept', 'basic concept', 'useful concept','shallow concept', 'major course', 'great concept', 'statistical technique','lot lecture', 'learned lot','good overview','fulfill topic', 'good role',
                 'deep topic', 'basic aspect', 'wide cover','wide aspect', 'tricky learn', 'good learn','good learning', 'good topic', 'wide variety', 'wide course', 'enjoyed course',  'top variety', 'top course', 
                 'wide knowledge', 'enjoyed knowledge', 'solid basic', 'excellent literacy', 'excellent style', 'solid style', 'basic style', 'engaging lively','good coverage', 'wide coverage', 'good range', 'wide range',
                 'easy interesting', 'easy video', 'interesting video', 'easy lecture', 'interesting lecture', 'useful genius', 'helpful genius', 'interactive session',  'familiar world', 'basic enormously', 'summary topic', 
                 'better topic', 'great taste','good ethic','ethic morality','good worth', 'worth everything', 'worth lot', 'good patience', 'worth patience', 'good study', 'worth study', 'recommend friend','informative knowledge',
                 'nice fun', 'nice take', 'nice math','bit math','great terminology', 'basic terminology','easy follow', 'easy professor','live help', 'little help', 'deeper math', 'excellent information', 'huge course', 
                 'huge learn', 'recommend course','easy online', 'hardest online','easy course', 'hardest course','good information', 'informative course', 'informative clarity', 'good clarity','informative good', 
                 'nice learn', 'better material', 'structuring material', 'great introductory','introductory course', 'great background', 'introductory background', 'good choice', 'good design', 'innovative course', 
                 'innovative design', 'excellent course', 'excellent learn', 'basic learn', 'happy course', 'happy everything', 'enjoyed wonderfully','specific quality', 'good content', 'good quality' , 
                 'informative engaging', 'minor technical','minor course', 'practical content', 'tailored', 'amazing professor','insightful and interesting', 'insightfuland interesting', 'knowledgeable course', 
                 'nice experience', 'nice learning',  'real simulation','intuitive introduction', 'best introduction', 'nice method', 'nice explanation','good example', 'insightful course', 'comprehensive interactive', 
                 'valuable beginner', 'amazing course', 'best course', 'interesting course', 'awesome course', 'basic perspective','professional perspective', 'different perspective', 'modern perspective','professional work', 
                 'different work', 'great watch', 'introductory watch', 'great group', 'great discussion', 'introductory discussion','learned technical', 'gained knowledge', 'good reality', 'gained reality', 'basic reality', 
                 'right course', 'right knowledge', 'right market', 'right application','good thought', 'gained thought', 'basic thought','right thought', 'popular online', 'popular course', 'popular knowledge', 'meaningful online', 
                 'meaningful course',  'meaningful knowledge', 'necessary online', 'necessary course', 'right skill', 'popular skill', 'meaningful skill', 'necessary skill', 'rational application','popular decision', 
                 'meaningful decision', 'necessary decision', 'rational decision','good future', 'future knowledge','future course', 'true application', 'true reality', 'true money', 'true opinion','educational knowledge',
                 'educational application', 'educational work', 'educational sector', 'important online', 'important course', 'important knowledge', 'rational professor','right professor','important professor', 'true amazing',
                 'mathematical course','great taught', 'great teach','theoretical experience', 'theoretical course','taught valued','great interest', 'great background', 'remote background', 'great simplicity', 'great relevance', 
                 'great instructor','great team','introductory topic','simple relevance', 'simple course', 'introductory understand', 'introductory content','indepth simplicity', 'indepth background', 'indepth topic','indepth content',
                 'insight topic', 'necessary background', 'necessary content', 'relevant interest', 'relevant point','insight behavior', 'great expression', 'introductory expression','simple expression', 'relevant expression',
                 'indepth policy','insight policy', 'relevant policy','great result','relevant result','great progress','insight reading','take today','simple bingewatching','necessary bingelearning','start level','need background',
                 'best relevance','useful help', 'useful decision', 'motivate student','little knowledge', 'difficult knowledge', 'foundational ability','informed application', 'build knowledge', 'passionate work','simple professor',
                 'passionate education', 'concept reading', 'wonderful concept', 'wonderful reading', 'concept course', 'lasted longer','essential course', 'essential basic', 'essential professor', 'complicate concept',
                 'easy professor', 'easy concept', 'great professor', 'useful superb','useful material', 'useful course', 'academic superb','academic material','useful perspective', 'academic perspective','superb overview',
                 'useful learning','difficult lecturer', 'modern professor', 'modern area', 'best experience', 'best field','best help', 'different information', 'fresh course', 'fresh work', 'fresh wealth', 'fresh perspective',
                 'familiar topic','fresh topic',  'fresh context', 'fresh picture', 'incredible course','incredible teacher', 'difficult teacher','incredible priceless', 'online priceless','great video', 'interesting video',
                 'comprehensive insightful', 'comprehensive inspiring', 'comprehensive introduction', 'insightful introduction', 'comprehensive learn', 'insightful learn','formidable learn', 'comprehensive expert', 
                 'insightful expert', 'expert learn', 'comprehensive area', 'insightful area',  'invaluable introduction','invaluable learn','invaluable course', 'formal learn', 'expert study', 'invaluable study',
                 'formal study','informal course','comprehensive professor', 'insightful professor', 'expert professor', 'invaluable professor', 'formal professor', 'informal professor','insightful traverse',
                 'expert delivering', 'comprehensive delivering','insightful delivering', 'expert witty','formal witty', 'comprehensive insightful', 'skillfully switching',  'paced understanding', 'great regulation',
                 'special environment', 'great environment', 'elaborate environment', 'paced environment','intense course','excellent involvement', 'intense involvement', 'multiple involvement', 'intense learn',
                 'excellent material', 'intense material','material course','material learn','wonderful appreciation', 'excellent course', 'broad course', 'excellent overview', 'broad overview',  'excellent theory', 
                 'broad theory', 'subject material','complete course', 'complete package', 'complete learn', 'deep review', 'deep surface', 'deep core', 'complete understanding', 'deep understanding', 'complete help', 
                 'deep help', 'professional course', 'professional package','encircled surface', 'fantastic course','humble course','fantastic teacher', 'humble teacher', 'intensive course','intensive experience',
                 'theoretical course', 'theoretical knowledge', 'recommend join','big benefit', 'concept course','highly recommend', 'better knowledge','clear insight','outstanding', 'enjoy', 'great information',
                 'generous course', 'generous information','crafted grasp', 'valuable course', 'great perspective','valuable perspective','crafted benefit', 'great benefit', 'generous benefit','crafted selection', 
                 'great selection', 'generous selection', 'responsible selection','short course', 'crafted addition', 'great addition', 'perspective helpful', 'crafted quiz', 'great quiz', 'crafted assignment', 
                 'great assignment', 'crafted ability', 'great ability', 'crafted grade', 'great grade', 'generous grade', 'appropriate course','crafted choice', 'great choice','tutorial focus','crafted reading',
                 'great reading', 'generous reading','best selection', 'best grade', 'best quiz','participant focus', 'easy lesson','vital derivative', 'smooth derivative', 'easy derivative','informational resource', 
                 'informational transparency','informational efficient','informational appropriate','efficient resource', 'appropriate resource', 'efficient price', 'appropriate price', 'intrinsic lesson','informational offering',
                 'efficient offering', 'appropriate offering', 'intrinsic offering','perfect course','perfect lecture', 'clear discussion', 'immense insight','wonderful professor', 'excellent study','logic course','great staff',
                 'interest field','useful field', 'good field','grasp valuation', 'high valuation','nice staff', 'informative overview', 'organised course','esteemed ability','good opinion','higher confidence','clear discipline',
                 'moderate confidence', 'low confidence','helpful information','optional course','invaluable course', 'productive session','knowledge charge','intriguing topic','true challenging','recommend professor',
                 'overall resourceful','worth idea','idea engineering','exceeded expectation','immense expectation','great introduction','limited learning','interesting introduction','matter background','strong principle',
                 'prerequisite course','suggested prerequisite','worthless course','real course','recommend class', 'common course', 'subject challenging', 'clear lecture', 'direct lecture','fundamental understanding',
                 'highly recommended','excellent introductory','high quality','wonderful heartfelt','meet objective','informative topic','instrument support', 'behavioural support', 'excellent support', 'excellent session', 
                 'wonderful professor','wonderful course', 'obvious work','upright technology','good technology','exceptional course', 'exceptional insight', 'exceptional experience', 'immersive capability','irreplaceable value',
                 'invaluable aspiration','penny worth','lucid curriculum', 'lucid explanation', 'lucid course', 'brilliant professor', 'highly informative','bias course', 'modern understanding', 'broad lecture','understandable view',
                 'informative concept', 'unique concept', 'practical course',  'outstanding job','outstanding teaching', 'wide overview', 'extensive overview','extensive course','macro overview','accessible module', 'accessible course', 
                 'accessible discussion','generally great', 'great prof', 'refresh thinking', 'interesting thinking', 'excellent comprehensive', 'good innovation', 'efficient innovation', 'holistic skill', 'terrible lecturer', 
                 'necessary explore','understanding professor',  'understanding concept','great humility', 'great understanding', 'poorly produced', 'simple language', 'oriented', 'interestingcourse content','pretty good',
                 'relevant', 'dont recommend', 'easy understand','enjoyed something','professional course','professional investment','incomplete lecture','little knowledge', 'invaluable professor','refresher style',
                 'engaging style', 'interactive course','pleased content','dry concept','outstanding teacher','outstanding mentor','work intensive', 'little intimidating','worthless lecture','real pathetic',
                 'horrible course', 'horrible content', 'unclear course', 'unclear content','awful course','superficial information','terrible information',
                 'awful feel', 'unusable understanding', 'selfexplanatory course', 'legitimate quiz','straight waste', 'monotonous pace', 'monotonous make', 'monotonous course', 'mundane pace', 'mundane course',
                 'time taking','tough understand', 'simple language', 'good investment','difficult deadline', 'reset deadline', 'deadline govern', 'deviate topic','completely deviate','different content', 'different course', 
                 'wide interestingcourse','high level','disorganized course','confused professor', 'confused course','unrelated lecture','unrelated material','handful knowledge', 'better knowledge', 'better topic',
                 'better concept','handful kind','broken concept', 'hard everything','hard course','hard follow', 'lesson content','good presentation', 'esteemed professor','beginner level','high review','overall basic',
                 'smooth conversation', 'smooth lecturer', 'overall transition', 'great transition',  'practical transition', 'smooth transition', 'fundamental course',
                 'academic instructor', 'effective opinion', 'effective course', 'useless', 'intense course', 'rich course', 'intense time', 'key perspective',
                 'knowledge perspective','informative explanation','wonderful explanation',  'informative field', 'wonderful field', 'mixed dilemma','offputting feeling',
                 'meaningful lecture','sufficient course', 'brilliant professor','interesting presentation', 'insufficient course','insufficient time','hard annoying',
                 'deep information', 'appreciate objective','appreciate course', 'topic outdated', 'broad classic','awesome pace', 'awesome lecture', 'great pace', 
                 'perspective lecture', 'informative nonetheless', 'investing nonetheless', 'informative term', 'interactive activity', 'interactive learning','alright course',
                 'capture interest', 'fails capture','wrong course', 'wrong expectation', 'great teacher', 'great understanding', 'understanding professor', 'overall hard', 
                 'enjoyed attend','found approachable', 'pretty generous', 'practical course', 'great value', 'academic value', 'practical value', 'deepen course', 'deepen value',
                 'reliable theory','applicable theory','intimidated course','various complexity', 'hard course','unprecedented chance','important course',
                 'worth course', 'worth praise','learned lot', 'excellent topic',  'excellent connotation', 'understanding technology','great future','great amazing',
                 'great thoughtful', 'thoughtful course', 'thoughtful professor','great explanation','useful information', 'useful class', 'huge idea', 'best class',
                 'unmatched topic', 'huge topic','huge privilege', 'best idea','single learner','unmatched experience','simple interesting', 'content benefit', 
                 'excellent benefit','lecture interesting','liked course', 'clear consise','clear course', 'understandable course','liked assignment','structured simple',
                 'structured assignment','interactive platform', 'excellent fusion', 'interactive fusion','platform interactive',  'exceptional concept', 'amazing concept', 
                 'noble concept','derivative course','informative sight', 'good sight','economic special', 'structured lecture','helpful understanding', 'helpful exercise', 
                 'practical exercise','better quality','complete beginner','understandable concept', 'better courseoverall','complete information', 'helpful information',
                 'significant recommend', 'immense concept','class staple', 'wonderful time', 'wonderful course','wrong curriculum','undergrad load', 
                 'intense class','hardest class','good class','good time','independent prep','outstanding class', 'reasonable class','intensive work', 
                 'great mentor','workintensive nice', 'double nice', 'super nice', 'hard workintensive', 'great caring','super help', 'nice help', 'super passionate',
                 'super sweet',  'easy professor', 'hard concept', 'hardest professor','knowledgeable class', 'worthy class','best professor','graduate quality',
                 'incredible person', 'incredible worth','amazing class','mind blowing', 'hard take', 'hard time', 'hardest class', 'super helpful', 'awful class',
                 'hardest work', 'good teacher', 'good homework', 'clear homework', 'repetitive homework',  'good answer', 'clear answer', 'repetitive answer', 
                 'clear attention', 'cool', 'median lecture','generously median','adorable helpful','helpful lecture', 'intensive material','intensive professor',
                 'intensive class', 'straightforward class','exam straightforward', 'straightforward lecture', 'isnt easiest','hard class', 'necessary book',
                 'tough section', 'tough material', 'found approachable', 'pretty generous', 'generous curve', 'easy matter', 'easy class', 'refreshing change',
                 'best described', 'described class', 'incredibly nice','nice guy','fair grader', 'boring sit','fair class','boring lecture','simple everyday',
                 'simple lecture', 'simple class','hard exam','hard challenge','sure misfortune','easy professor','easy class','good approach','understand approach',
                 'fine class', 'highly engaging', 'fun interesting','great lecture','interesting content','excellent overall', 'excellent course', 'excellent content',
                 'excellent faculty','perfect course', 'perfect content', 'perfect professor','best opportunity','learnt lot','worthless course','worthless concept', 
                 'poor concept','unsuccessful attempt','brand pathetic','straight waste', 'waste time', 'difficult deadline','difficult troubleshoot','difficult quiz',
                 'deviate topic', 'disappointed topic', 'disappointed course', 'completely deviate','good presentation', 'essential information', 'hard information',
                 'effective','useless', 'indepth lesson', 'pleasant style','concept complex', 'problematic material','problematic class', 'expect improvement','general kind',
                 'modern thinking','practical course','innovative thinking','good skill','great experience','practical course', 'good morality','great speaker', 
                 'insightful', 'interesting', 'nice learning','technical course', 'low confidence', 'great learning','excellent introductory','excellent lecturer', 
                 'immense knowledge','informed course', 'sincere professor', 'valuable course', 'cool course','terrible course','poorly produced', 'disjointed lecture',
                 'informative', 'nice', 'useful study', 'good opportunity', 'unwatchable lecture', 'knowledgeable instructor', 'global course', 'beginner overview', 'extraordinary course', 'wonderful experience']
                 
def freq_words(x, terms = 30):
  all_words = ' '.join([text for text in x])
  all_words = all_words.split()
  
  fdist = nltk.FreqDist(all_words)
  words_df = pd.DataFrame({'word':list(fdist.keys()), 'count':list(fdist.values())})
  
  # selecting top 20 most frequent words
  d = words_df.nlargest(columns="count", n = terms) 
  print(d)
  
def data_cleanse(line):
# Removes all special characters and numericals leaving the alphabets
    line = line.lower()
    line = re.sub('@', '', line)
    line = re.sub('\[.*?\]', '', line)
    line = re.sub('https?://\S+|www\.\S+', '', line)
    line = re.sub('<.*?>+', '', line)
    line = re.sub('[%s]' % re.escape(string.punctuation), '', line)
    line = re.sub('\n', '', line)
    line = re.sub('\w*\d\w*', '', line)
    line = re.sub(r"[^a-zA-Z ]+", "", line)
    
    #Tokenize the data
    line = nltk.word_tokenize(line)
    #Remove stopwords
    line = [w for w in line if w not in stopwords]
    line = [spell(w) for w in line]
    final = ' '.join(line)
    return final.lower()

def select_columns(data_frame, column_names):
    new_frame = data_frame.loc[:, column_names]
    return new_frame

def feature_buildtext(line):
    
    allFeatures_list = []
    lineVal = str(line)
    data = []
    r.extract_keywords_from_text(lineVal)
    dataKeys = r.get_ranked_phrases()[:10]
    print(dataKeys[0])
    for w in dataKeys[0].split(): 
      data.append(w)
      if len(data) != 0:
        adjective = nltk.pos_tag(data)
        for nn_val in [item for item in adjective if item[1] == 'NN']:
          for jj_val in [item for item in adjective if item[1] in ['JJ', 'JJR', 'JJS']]:
            keyPhrase = jj_val[0] +' '+ nn_val[0];
            if keyPhrase not in allFeatures_list:
              allFeatures_list.append(keyPhrase) 
    return allFeatures_list

# import spaCy's language model
nlp = spacy.load('en')
multilabel_binarizer = MultiLabelBinarizer()
tfidf = TfidfVectorizer(tokenizer=feature_buildtext,max_df=0.8, max_features=100000)
r = Rake()

# Lemmatize the reviews
lemmatizer = WordNetLemmatizer()
def lem(line):
    mwords = []
    for word in line.split(" "):
      line = lemmatizer.lemmatize(word)
      mwords.append(line)
    return ' '.join(mwords)


def data_keyword_extract(line):
    lineVal = str(line)
    data = []
    keywordList = []
    newPhraseList = []
    normal = 1
    r.extract_keywords_from_text(lineVal)
    dataKeys = r.get_ranked_phrases()[:5]
    if normal == 1:
      if len(dataKeys) > 0:
        for w in dataKeys[0].split(" "):
          data.append(w)
          if len(data) != 0:
            adjective = nltk.pos_tag(data)
            for nn_val in [item for item in adjective if item[1] == 'NN']:
              for jj_val in [item for item in adjective if item[1] in ['JJ', 'JJR', 'JJS']]:
                keyPhrase = jj_val[0] +' '+ nn_val[0];
                if keyPhrase not in newPhraseList:
                  if keyPhrase in selected_list:
                    newPhraseList.append(keyPhrase) 
      kw_extractor = yake.KeywordExtractor(lan="en", n=2, dedupLim=0.1, top=2, features=None)
      dataKeys = kw_extractor.extract_keywords(lineVal)[:2]
      for phrs in list(map(lambda x: x[0], dataKeys)):
        if phrs in selected_list:
          if phrs not in newPhraseList:
            newPhraseList.append(phrs)
    return newPhraseList

def data_keyword_extract_yake(line):
    lineVal = str(line)
    data = []
    keywordList = []
    ######yake
    kw_extractor = yake.KeywordExtractor(lan="en", n=2, dedupLim=0.9, top=2, features=None)
    dataKeys = kw_extractor.extract_keywords(lineVal)[:2]
    keywordList = list(map(lambda x: x[0], dataKeys))
    
    return keywordList
   
def build_model():
    url_data = (r'https://raw.githubusercontent.com/rps2ff23/CourseProject/main/sentiment-analysis/Coursera_reviews_subset.csv')
    
    coursedata_train = pd.read_csv(url_data, engine='python', error_bad_lines=False).dropna()
    coursedata_train = coursedata_train.drop_duplicates(subset = ['reviews', "course_id"])

    #print(coursedata_train.columns.tolist())

    url_data = (r'https://raw.githubusercontent.com/rps2ff23/CourseProject/main/sentiment-analysis/spreadsheet.csv')
    proffessordata_train = pd.read_csv(url_data, engine='python',header='infer',error_bad_lines=False).dropna()
    proffessordata_train = proffessordata_train.drop_duplicates(subset = ['comment'])
    #print(proffessordata_train.columns.tolist())

    data_train_1 = select_columns(coursedata_train, ['reviews']) #Course Feedback
    data_train_2 = select_columns(proffessordata_train, ['comment']).rename(columns = {'comment' : 'reviews'}) #Professor feedback

    #Combine professor feedback and course feedback
    data_train_1 = data_train_1.append(data_train_2)
    data_train = data_train_1.reset_index()

    #print(len(data_train_1), len(data_train_2))
    data_train.replace(to_replace=r'[\n\r\t]', value='', regex=True, inplace=True)

    data_train['Cleaned Reviews'] = data_train['reviews'].apply(data_cleanse)
    data_train.reset_index()
    
    final_data = select_columns(data_train, ['Cleaned Reviews'])
    final_data = final_data.drop_duplicates(subset="Cleaned Reviews")
    final_data = final_data.reset_index()
    
    final_data['Cleaned Reviews'] = final_data['Cleaned Reviews'].apply(lem)

    # Key word extraction
    feature_list = []

    # Uses stopwords for english from NLTK, and all puntuation characters by
    # default
    final_data['keyword'] = final_data['Cleaned Reviews'].apply(data_keyword_extract)
    final_data_subset = final_data[final_data['keyword'].apply(lambda x: len(x)) > 0]

    final_data = final_data_subset.reset_index()
    
    # Build Model
    # Using keyword based multilable binarizer
    multilabel_binarizer.fit(final_data['keyword'])
    y = multilabel_binarizer.transform(final_data['keyword'])
    #print(y)

    # split dataset into training and validation set

    xtrain, xval, ytrain, yval = train_test_split(final_data['Cleaned Reviews'],y, test_size=0.2, random_state=9)

    xtrain_tfidf = tfidf.fit_transform(xtrain)
    xval_tfidf =  tfidf.transform(xval)

    lr = LogisticRegression()
    clf = OneVsRestClassifier(lr)
    # fit model on train data
    clf.fit(xtrain_tfidf, ytrain)

    # save the model and other parameters to disk and use this in the final script
    pickle.dump([clf, tfidf, multilabel_binarizer] , open('finalized_model.sav', 'wb'))

    
    #Check accuracy_score
    print("Accuracy:",metrics.accuracy_score(yval[10], y_pred[10]))
    print("Accuracy:",metrics.accuracy_score(yval[384], y_pred[384]))

if __name__ == "__main__":

    build_model()